### ISSUE TITLE
Things todo post-publish

### ISSUE THREAD

**Issue by chengcli** [zoeyzyhu/pydisort#42]
- [x]  Requirement, only allow installation > 3.8
We only support python 3.8 and upwards. pip install will **FAIL** if the python library version is less than 3.8.

- [x]  How to upgrade python version on Mac
Give instruction on how to upgrade python on Mac, Ubuntu, and Redhat

- [x]  Reinstall CI on pydisort 
Currently, CI does not work. Reinstall CI by **NOT CHECKING** setup.py

- [x]  Readme 
Update README on pypi.org. Make sure that we DO NOT support conda or anaconda at this moment.
We will support conda/Anaconda support with source code distribution.

- [x] If possible, check OS system during pip install. pip install shall **FAIL** if OS is not Ubunru or Redhat
